name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23li25dHHVnhWJsS9G"
GITHUB_OWNER = "zealike"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://navsphere-amm.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://navsphere-amm.pages.dev/"

